(ns click2school.views.otherpages
  (:require [click2school.views.common :as common]
            [click2school.models.user :as user]
            [noir.response :as resp]
            [noir.session :as session])
  (:use [noir.core :only [defpage url-for render]]
        [click2school.views.messages :only (message-inbox)]))

(defpage instant-messages "/instant" []
  (common/layout-with-navbar-and-sidebar
    (common/default-navbar (session/get :username ))
    (common/sidebar (common/sidebar-section-header "Communication")
                    (common/sidebar-item (url-for message-inbox) "Messages" :inbox)
                    (common/sidebar-item (url-for instant-messages) "Instant Messages" :comment :active)
                    (common/sidebar-item (url-for emails) "Emails" :envelope)
                    (common/sidebar-item (url-for phone-calls) "Phone Calls" :inbox)
                    (common/sidebar-section-header "Calendar")
                    (common/sidebar-item (url-for meetings) "Meetings" :user)
                    (common/sidebar-item (url-for papers-due) "Papers Due" :file)
                    (common/sidebar-section-header "Quizzes")
                    (common/sidebar-item (url-for quizz1) "Quizz 1" :star)
                    (common/sidebar-item (url-for quizz2) "Quizz 2" :empty)
                    (common/sidebar-item (url-for quizz3) "Quizz 3" :heart)
                    (common/sidebar-section-header "Administration")
                    (common/sidebar-item (url-for students) "Students" :folder-close)
                    (common/sidebar-item (url-for classes) "Classes" :leaf))
    [:h1 "Instant Messages"]))

(defpage emails "/emails" []
  (common/layout-with-navbar-and-sidebar
    (common/default-navbar (session/get :username ))
    (common/sidebar (common/sidebar-section-header "Communication")
                    (common/sidebar-item (url-for message-inbox) "Messages" :inbox)
                    (common/sidebar-item (url-for instant-messages) "Instant Messages" :comment)
                    (common/sidebar-item (url-for emails) "Emails" :envelope :active)
                    (common/sidebar-item (url-for phone-calls) "Phone Calls" :inbox)
                    (common/sidebar-section-header "Calendar")
                    (common/sidebar-item (url-for meetings) "Meetings" :user)
                    (common/sidebar-item (url-for papers-due) "Papers Due" :file)
                    (common/sidebar-section-header "Quizzes")
                    (common/sidebar-item (url-for quizz1) "Quizz 1" :star)
                    (common/sidebar-item (url-for quizz2) "Quizz 2" :empty)
                    (common/sidebar-item (url-for quizz3) "Quizz 3" :heart)
                    (common/sidebar-section-header "Administration")
                    (common/sidebar-item (url-for students) "Students" :folder-close)
                    (common/sidebar-item (url-for classes) "Classes" :leaf))
   [:h1 "Emails"]))

(defpage phone-calls "/phonecalls" []
  (common/layout-with-navbar-and-sidebar
    (common/default-navbar (session/get :username ))
    (common/sidebar (common/sidebar-section-header "Communication")
                    (common/sidebar-item (url-for message-inbox) "Messages" :inbox)
                    (common/sidebar-item (url-for instant-messages) "Instant Messages" :comment)
                    (common/sidebar-item (url-for emails) "Emails" :envelope)
                    (common/sidebar-item (url-for phone-calls) "Phone Calls" :inbox :active)
                    (common/sidebar-section-header "Calendar")
                    (common/sidebar-item (url-for meetings) "Meetings" :user)
                    (common/sidebar-item (url-for papers-due) "Papers Due" :file)
                    (common/sidebar-section-header "Quizzes")
                    (common/sidebar-item (url-for quizz1) "Quizz 1" :star)
                    (common/sidebar-item (url-for quizz2) "Quizz 2" :empty)
                    (common/sidebar-item (url-for quizz3) "Quizz 3" :heart)
                    (common/sidebar-section-header "Administration")
                    (common/sidebar-item (url-for students) "Students" :folder-close)
                    (common/sidebar-item (url-for classes) "Classes" :leaf))
    [:h1 "Phone Calls"]))

(defpage meetings "/meetings" []
  (common/layout-with-navbar-and-sidebar
    (common/default-navbar (session/get :username ))
    (common/sidebar (common/sidebar-section-header "Communication")
                    (common/sidebar-item (url-for message-inbox) "Messages" :inbox)
                    (common/sidebar-item (url-for instant-messages) "Instant Messages" :comment)
                    (common/sidebar-item (url-for emails) "Emails" :envelope)
                    (common/sidebar-item (url-for phone-calls) "Phone Calls" :inbox)
                    (common/sidebar-section-header "Calendar")
                    (common/sidebar-item (url-for meetings) "Meetings" :user :active)
                    (common/sidebar-item (url-for papers-due) "Papers Due" :file)
                    (common/sidebar-section-header "Quizzes")
                    (common/sidebar-item (url-for quizz1) "Quizz 1" :star)
                    (common/sidebar-item (url-for quizz2) "Quizz 2" :empty)
                    (common/sidebar-item (url-for quizz3) "Quizz 3" :heart)
                    (common/sidebar-section-header "Administration")
                    (common/sidebar-item (url-for students) "Students" :folder-close)
                    (common/sidebar-item (url-for classes) "Classes" :leaf))
    [:h1 "Meetings"]))

(defpage papers-due "/papers" []
  (common/layout-with-navbar-and-sidebar
    (common/default-navbar (session/get :username ))
    (common/sidebar (common/sidebar-section-header "Communication")
                    (common/sidebar-item (url-for message-inbox) "Messages" :inbox)
                    (common/sidebar-item (url-for instant-messages) "Instant Messages" :comment)
                    (common/sidebar-item (url-for emails) "Emails" :envelope)
                    (common/sidebar-item (url-for phone-calls) "Phone Calls" :inbox)
                    (common/sidebar-section-header "Calendar")
                    (common/sidebar-item (url-for meetings) "Meetings" :user)
                    (common/sidebar-item (url-for papers-due) "Papers Due" :file :active)
                    (common/sidebar-section-header "Quizzes")
                    (common/sidebar-item (url-for quizz1) "Quizz 1" :star)
                    (common/sidebar-item (url-for quizz2) "Quizz 2" :empty)
                    (common/sidebar-item (url-for quizz3) "Quizz 3" :heart)
                    (common/sidebar-section-header "Administration")
                    (common/sidebar-item (url-for students) "Students" :folder-close)
                    (common/sidebar-item (url-for classes) "Classes" :leaf))
    [:h1 "Papers Due"]))

(defpage quizzes "/quizzes" []
  (common/layout-with-navbar-and-sidebar
    (common/default-navbar (session/get :username ))
    (common/sidebar (common/sidebar-section-header "Communication")
                    (common/sidebar-item (url-for message-inbox) "Messages" :inbox)
                    (common/sidebar-item (url-for instant-messages) "Instant Messages" :comment)
                    (common/sidebar-item (url-for emails) "Emails" :envelope)
                    (common/sidebar-item (url-for phone-calls) "Phone Calls" :inbox)
                    (common/sidebar-section-header "Calendar")
                    (common/sidebar-item (url-for meetings) "Meetings" :user)
                    (common/sidebar-item (url-for papers-due) "Papers Due" :file)
                    (common/sidebar-section-header "Quizzes")
                    (common/sidebar-item (url-for quizz1) "Quizz 1" :star)
                    (common/sidebar-item (url-for quizz2) "Quizz 2" :empty)
                    (common/sidebar-item (url-for quizz3) "Quizz 3" :heart)
                    (common/sidebar-section-header "Administration")
                    (common/sidebar-item (url-for students) "Students" :folder-close)
                    (common/sidebar-item (url-for classes) "Classes" :leaf))
    [:h1 "Quizzes"]))

(defpage quizz1 "/quizz/1" []
  (common/layout-with-navbar-and-sidebar
    (common/default-navbar (session/get :username ))
    (common/sidebar (common/sidebar-section-header "Communication")
                    (common/sidebar-item (url-for message-inbox) "Messages" :inbox)
                    (common/sidebar-item (url-for instant-messages) "Instant Messages" :comment )
                    (common/sidebar-item (url-for emails) "Emails" :envelope)
                    (common/sidebar-item (url-for phone-calls) "Phone Calls" :inbox)
                    (common/sidebar-section-header "Calendar")
                    (common/sidebar-item (url-for meetings) "Meetings" :user)
                    (common/sidebar-item (url-for papers-due) "Papers Due" :file)
                    (common/sidebar-section-header "Quizzes")
                    (common/sidebar-item (url-for quizz1) "Quizz 1" :star :active)
                    (common/sidebar-item (url-for quizz2) "Quizz 2" :empty)
                    (common/sidebar-item (url-for quizz3) "Quizz 3" :heart)
                    (common/sidebar-section-header "Administration")
                    (common/sidebar-item (url-for students) "Students" :folder-close)
                    (common/sidebar-item (url-for classes) "Classes" :leaf))
    [:h1 "Quizz 1"]))

(defpage quizz2 "/quizz/2" []
  (common/layout-with-navbar-and-sidebar
    (common/default-navbar (session/get :username ))
    (common/sidebar (common/sidebar-section-header "Communication")
                    (common/sidebar-item (url-for message-inbox) "Messages" :inbox)
                    (common/sidebar-item (url-for instant-messages) "Instant Messages" :comment)
                    (common/sidebar-item (url-for emails) "Emails" :envelope)
                    (common/sidebar-item (url-for phone-calls) "Phone Calls" :inbox)
                    (common/sidebar-section-header "Calendar")
                    (common/sidebar-item (url-for meetings) "Meetings" :user)
                    (common/sidebar-item (url-for papers-due) "Papers Due" :file)
                    (common/sidebar-section-header "Quizzes")
                    (common/sidebar-item (url-for quizz1) "Quizz 1" :star)
                    (common/sidebar-item (url-for quizz2) "Quizz 2" :empty :active)
                    (common/sidebar-item (url-for quizz3) "Quizz 3" :heart)
                    (common/sidebar-section-header "Administration")
                    (common/sidebar-item (url-for students) "Students" :folder-close)
                    (common/sidebar-item (url-for classes) "Classes" :leaf))
    [:h1 "Quizz 2"]))

(defpage quizz3 "/quizz/3" []
  (common/layout-with-navbar-and-sidebar
    (common/default-navbar (session/get :username ))
    (common/sidebar (common/sidebar-section-header "Communication")
                    (common/sidebar-item (url-for message-inbox) "Messages" :inbox)
                    (common/sidebar-item (url-for instant-messages) "Instant Messages" :comment)
                    (common/sidebar-item (url-for emails) "Emails" :envelope)
                    (common/sidebar-item (url-for phone-calls) "Phone Calls" :inbox)
                    (common/sidebar-section-header "Calendar")
                    (common/sidebar-item (url-for meetings) "Meetings" :user)
                    (common/sidebar-item (url-for papers-due) "Papers Due" :file)
                    (common/sidebar-section-header "Quizzes")
                    (common/sidebar-item (url-for quizz1) "Quizz 1" :star)
                    (common/sidebar-item (url-for quizz2) "Quizz 2" :empty)
                    (common/sidebar-item (url-for quizz3) "Quizz 3" :heart :active)
                    (common/sidebar-section-header "Administration")
                    (common/sidebar-item (url-for students) "Students" :folder-close)
                    (common/sidebar-item (url-for classes) "Classes" :leaf))
    [:h1 "Quizz 3"]))

(defpage students "/students" []
  (common/layout-with-navbar-and-sidebar
    (common/default-navbar (session/get :username ))
    (common/sidebar (common/sidebar-section-header "Communication")
                    (common/sidebar-item (url-for message-inbox) "Messages" :inbox)
                    (common/sidebar-item (url-for instant-messages) "Instant Messages" :comment)
                    (common/sidebar-item (url-for emails) "Emails" :envelope)
                    (common/sidebar-item (url-for phone-calls) "Phone Calls" :inbox)
                    (common/sidebar-section-header "Calendar")
                    (common/sidebar-item (url-for meetings) "Meetings" :user)
                    (common/sidebar-item (url-for papers-due) "Papers Due" :file)
                    (common/sidebar-section-header "Quizzes")
                    (common/sidebar-item (url-for quizz1) "Quizz 1" :star)
                    (common/sidebar-item (url-for quizz2) "Quizz 2" :empty)
                    (common/sidebar-item (url-for quizz3) "Quizz 3" :heart)
                    (common/sidebar-section-header "Administration")
                    (common/sidebar-item (url-for students) "Students" :folder-close :active)
                    (common/sidebar-item (url-for classes) "Classes" :leaf))
    [:h1 "Students"]))

(defpage classes "/classes" []
  (common/layout-with-navbar-and-sidebar
    (common/default-navbar (session/get :username ))
    (common/sidebar (common/sidebar-section-header "Communication")
                    (common/sidebar-item (url-for message-inbox) "Messages" :inbox)
                    (common/sidebar-item (url-for instant-messages) "Instant Messages" :comment)
                    (common/sidebar-item (url-for emails) "Emails" :envelope)
                    (common/sidebar-item (url-for phone-calls) "Phone Calls" :inbox)
                    (common/sidebar-section-header "Calendar")
                    (common/sidebar-item (url-for meetings) "Meetings" :user)
                    (common/sidebar-item (url-for papers-due) "Papers Due" :file)
                    (common/sidebar-section-header "Quizzes")
                    (common/sidebar-item (url-for quizz1) "Quizz 1" :star)
                    (common/sidebar-item (url-for quizz2) "Quizz 2" :empty)
                    (common/sidebar-item (url-for quizz3) "Quizz 3" :heart)
                    (common/sidebar-section-header "Administration")
                    (common/sidebar-item (url-for students) "Students" :folder-close)
                    (common/sidebar-item (url-for classes) "Classes" :leaf :active))
    [:h1 "Classes"]))






